
package menu;

/**
 * SELECCIONA ENTRE UN JUEGO DE LOS QUE SE ENCUENTRAN DISPONIBLES 
 * @author Willy Bazan
 * @date   10/12/2019
 * @time   06:38 pm
 */

import Main.Window;
import java.awt.Image;
import java.awt.Toolkit;
        
public class ChooseGame extends javax.swing.JFrame {

    /**
     * Creates new form ChooseGame
     */
    public ChooseGame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage() 
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Assets/iconoMecatronica.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btReturn = new javax.swing.JButton();
        btJuego0 = new javax.swing.JButton();
        btJuego1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelJuego1 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(600, 421));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btExit.setBackground(new java.awt.Color(255, 153, 51));
        btExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btExit.setForeground(new java.awt.Color(0, 0, 51));
        btExit.setText("EXIT");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        getContentPane().add(btExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        btReturn.setBackground(new java.awt.Color(255, 153, 51));
        btReturn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btReturn.setForeground(new java.awt.Color(0, 0, 51));
        btReturn.setText("RETURN");
        btReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btJuego0.setBackground(new java.awt.Color(6, 41, 65));
        btJuego0.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btJuego0.setForeground(new java.awt.Color(255, 255, 255));
        btJuego0.setText("PLAY");
        btJuego0.setPreferredSize(new java.awt.Dimension(70, 30));
        btJuego0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJuego0ActionPerformed(evt);
            }
        });
        getContentPane().add(btJuego0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        btJuego1.setBackground(new java.awt.Color(6, 41, 65));
        btJuego1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btJuego1.setForeground(new java.awt.Color(255, 255, 255));
        btJuego1.setText("PLAY");
        btJuego1.setPreferredSize(new java.awt.Dimension(70, 30));
        btJuego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJuego1ActionPerformed(evt);
            }
        });
        getContentPane().add(btJuego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        jButton2.setBackground(new java.awt.Color(5, 40, 64));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PLAY");
        jButton2.setPreferredSize(new java.awt.Dimension(70, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, -1, -1));

        jLabelJuego1.setIcon(new javax.swing.ImageIcon("D:\\GAUSS\\PROYECTOS\\JAVA\\MENU\\src\\Assets\\1.png")); // NOI18N
        jLabelJuego1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 102, 153)));
        getContentPane().add(jLabelJuego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 260, 190));

        jLabelTitle.setBackground(new java.awt.Color(153, 92, 63));
        jLabelTitle.setFont(new java.awt.Font("Harlow Solid Italic", 1, 50)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 102, 102));
        jLabelTitle.setText("Mechatronic Games");
        jLabelTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 490, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dutch801 XBd BT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 102, 0));
        jLabel4.setText("A KAAL IN SPACE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\GAUSS\\PROYECTOS\\JAVA\\MENU\\src\\Assets\\B.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 200, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\GAUSS\\PROYECTOS\\JAVA\\MENU\\src\\Assets\\fondoGame.PNG")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(23, 52, 102), new java.awt.Color(7, 48, 57), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void btReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReturnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btReturnActionPerformed

    
    
    private void btJuego0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJuego0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btJuego0ActionPerformed

    private void btJuego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJuego1ActionPerformed
        this.setVisible(false);
        Main.Window juego1 = new Window();
        juego1.empieza();
    }//GEN-LAST:event_btJuego1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btJuego0;
    private javax.swing.JButton btJuego1;
    private javax.swing.JButton btReturn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelJuego1;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
