/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Image;
import java.awt.Toolkit;

/**
 * ACCEDE A TODAS LOS JUEGOS 
 * @author Willy Bazan
 * @date   10/12/2019
 * @time   07:29 am
 */

public class Login extends javax.swing.JFrame {

    String user, password;
    boolean flagUser = false;  //Para indicar si el usuario ingreso los datos de manera correcta
    boolean flagPassword = false;
    String [] users = new String[4];
    String [] passwords = new String[4];
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Declaramos los nombres de los usarios
        users[0] = "KAAL";
        users[1] = "JORDI"; 
        users[2] = "CHIPI";
        users[3] = "RUIZ";
        
        //Declaramos las contraseñas permitidas
        passwords[0] = "A KAAL IN SPACE";
        passwords[1] = "JORDI";
        passwords[2] = "CHIPI";
        passwords[3] = "RUIZ";
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Assets/iconoMecatronica.jpg"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btExit = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextUser = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btExit.setBackground(new java.awt.Color(255, 153, 51));
        btExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btExit.setForeground(new java.awt.Color(255, 255, 255));
        btExit.setText("EXIT");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        getContentPane().add(btExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N
        getContentPane().add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, -1));

        jLabelUser.setBackground(new java.awt.Color(0, 51, 51));
        jLabelUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(255, 255, 51));
        jLabelUser.setText("USER :");
        getContentPane().add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, 20));

        jLabelPassword.setBackground(new java.awt.Color(102, 102, 0));
        jLabelPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 0));
        jLabelPassword.setText("PASSWORD :");
        getContentPane().add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jTextUser.setBackground(new java.awt.Color(0, 0, 51));
        jTextUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 220, -1));

        jPassword.setBackground(new java.awt.Color(0, 0, 51));
        jPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 220, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ACCEPT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("D:\\GAUSS\\PROYECTOS\\JAVA\\MENU\\src\\Assets\\fondoLogin.png")); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void jTextUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        user = jTextUser.getText();
        char[] arrayC = jPassword.getPassword();
        password = new String(arrayC);
        
        int index = 0;
        
        for ( String usuario : users)
        {
            
            if ( usuario.equals(user))
            {
                flagUser = true;
            } 
            
            if ( flagUser == true)
            {
                if ( passwords[index].equals(password))
                    flagPassword = true;
                    index = 0;
                    break;
            }
            
            index++;
        }
        
        if ( flagPassword == true)
        {
            ChooseGame chooseGame = new ChooseGame();
            chooseGame.setVisible(true);
            this.setVisible(false);
        }
        
        flagUser = false;
        flagPassword = false;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextUser;
    // End of variables declaration//GEN-END:variables
}
